apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: user-db-pipelinerun 
spec:
  pipelineRef:
    name: user-db-pipeline
  resources:
    - name: project-level3
      resourceRef:
        name: user-db-src
  params:
    - name: CONTEXT
      value: "/workspace/project-level3/user/docker/user-db"
    - name: DOCKERFILE
      value: "/workspace/project-level3/user/docker/user-db/Dockerfile"
    - name: pathToYamlFile
      value: "project-level3/user/tasks/task-db/userdb.yaml"
    - name: imageUrl
      value: "walaafahad/user-db"
    - name: imageTag
      value: "latest"
    - name: IMAGE
      value: "walaafahad/user-db"
      
  serviceAccountName: front-svc-acc