apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: orders-pipeline
spec:
  resources:
    - name: order-resource
      type: git
  tasks:
    - name: build
      taskRef:
        name: order
      resources:
        inputs: 
        - name: order-resource
          resource: order-resource
    - name: orders-deploy-kubectl
      runAfter: ["build"]
      taskRef:
        name: orders-deploy-kubectl
      resources:
        inputs:
        - name: order-resource
          resource: order-resource
