apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: catlogdb-final-run
spec:
  serviceAccountName: front-svc-acc
  pipelineRef:
    name:  catlogdb-pipeline
  resources:
    - name: catalogue-resource
      resourceRef:
        name: catalogue-resource