apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: catalogue-db-pipelinerun 
spec:
  pipelineRef:
    name: catalogue-db-pipeline
  resources:
    - name: project-level3
      resourceRef:
        name: catalogue-db-src
  params:
    - name: CONTEXT
      value: "/workspace/project-level3/catalogue/catalogue-db"
    - name: DOCKERFILE
      value: "/workspace/project-level3/catalogue/catalogue-db/Dockerfile"
    - name: pathToYamlFile
      value: "project-level3/catalogue/tasks/catalogdb.yaml"
    - name: imageUrl
      value: "walaafahad/catalogue-db"
    - name: imageTag
      value: "latest"
    - name: IMAGE
      value: "walaafahad/catalogue-db"
      
  serviceAccountName: front-svc-acc