apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: tekton-kn-sample-
spec:
  pipelineRef:
    name: build-and-deploy-pipeline
  resources:
    - name: level3-project
      resourceRef:
        name: front-end-git
  params:
    - name: pathToContext
      value: /workspace/level3-project/front-end
    - name: pathToYamlFile
      value: level3-project/front-end/front-end-deployemnt.yaml
    - name: imageUrl
      value: "walaafahad/front-end"
    - name: imageTag
      value: "latest"
  trigger:
    type: manual
  serviceAccount: pipeline-account
