apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: front-end-run
spec:
  serviceAccountName: walaa-dockerhub
  taskRef:
    name: front-end-run
  params:
  - name: IMAGE
    value: "walaafahad/front-end"
  resources:
    inputs:
    - name: level-3-project
      resourceRef:
        name: front-end-git
 
