apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: catalogue-run
spec:
  serviceAccountName: front-svc-acc
  pipelineRef:
    name: catalogue-pipeline
  resources:
    - name: catalogue-resource
      resourceRef:
        name: catalogue-resource