apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: carts-run
spec:
  serviceAccountName: cart-svc-acc
  pipelineRef:
    name: carts-pipeline
  resources:
    - name: carts-resource
      resourceRef:
        name: carts-resource
