apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: carts-pipelinerun 
spec:
  pipelineRef:
    name: carts-pipeline
  resources:
    - name: project-level3
      resourceRef:
        name: carts-src
  params:
    - name: CONTEXT
      value: "/workspace/project-level3/carts"
    - name: DOCKERFILE
      value: "/workspace/project-level3/carts/Dockerfile"
    - name: pathToYamlFile
      value: "project-level3/carts/tasks/cart-svc.yaml"
    - name: imageUrl
      value: "walaafahad/carts"
    - name: imageTag
      value: "latest"
    - name: IMAGE
      value: "walaafahad/carts"
      
  serviceAccountName: front-svc-acc