apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: carts-pipeline
spec:
  resources:
    - name: level3-project
      type: git
  tasks:
    - name: build
      taskRef:
        name: carts
      resources:
        inputs: 
        - name: level3-project
          resource:  carts-resource
    - name: carts-deploy-kubectl
      runAfter: ["build"]
      taskRef:
        name: carts-deploy-kubectl
      resources:
        inputs:
        - name: level3-project
          resource:  carts-resource
