apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: carts-taskrun
spec:
  serviceAccountName: cart-svc-acc 
  taskRef:
    name: carts
  params:
  - name: IMAGE
    value: "walaafahad/carts"
  resources:
    inputs:
    - name: carts-resource
      resourceRef:
        name: carts-resource 
