apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: front-end-run
spec:
  serviceAccountName: front-svc-acc
  pipelineRef:
    name: front-end-pipeline 
  resources:
    - name: source-git
      resourceRef:
        name: source-git
