apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: front-end-deploy-kubectl
  serviceAccountName: sock-shop
spec:
  params:
    - name: pathToYamlFile
      type: string
      description: The path to the yaml file to deploy within the git source
      default: $(resources.inputs.source-git.path)/front-end/front-end-deployemnt.yaml
    - name: namespace
      default: test
  resources:
    inputs:
      - name: source-git
        type: git
  steps:
   - name: run-kubectl
     image: lachlanevenson/k8s-kubectl
     command: ["kubectl"]
     args:
       - "apply"
       - "-f"
       - "$(params.pathToYamlFile)"
       - "-n"
       - "$(params.namespace)"
