apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: user-src
spec:
  type: git
  params:
    - name: revision
      value: main
    - name: url
      value: https://github.com/Awraad/project-level3