apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: user-db-run-images
spec:
  serviceAccountName: user-svc-acc
  taskRef:
    name: user-db
  resources:
    inputs:
    - name: user-resource
      resourceRef:
        name: user-resource
  params:
    - name: IMAGE
      value: "walaafahad/user-db"
