apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: userdb-pipeline
spec:
  resources:
    - name: user-resource
      type: git
  tasks:
    - name: build
      taskRef:
        name: user-db
      resources:
        inputs: 
        - name: user-resource
          resource: user-resource
    - name:  user-db-deploy-kubectl
      runAfter: ["build"]
      taskRef:
        name: user-deploy-kubectl
      resources:
        inputs:
        - name: user-resource
          resource: user-resource

