apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: e2e-test-pipeline
spec:
  resources:
    - name: project-level3
      type: git
  params:
    - name: IMAGE
      type: string
      default: "walaafahad/e2e-tests"
    - name: DOCKERFILE
      type: string
      default: "/workspace/project-level3/e2e-tests/Dockerfile"
    - name: CONTEXT
      type: string
      default: "/workspace/project-level3/e2e-tests"
    - name: imageUrl
      type: string
      default: "walaafahad/e2e-tests"
    - name: imageTag
      type: string
      default: "latest"
  tasks:
  - name: build-push-image
    taskRef:
      name: build-push-test
    params:
      - name: IMAGE
        value: "$(params.IMAGE)"
      - name: DOCKERFILE
        value: "$(params.DOCKERFILE)"
      - name: CONTEXT
        value: "$(params.CONTEXT)"
    resources:
      inputs:
        - name: project-level3
          resource: project-level3
  - name: run-test
    taskRef:
      name: e2e-task-run
    runAfter:
      - build-push-image
    params:
      - name: imageUrl
        value: "$(params.imageUrl)"
      - name: imageTag
        value: "$(params.imageTag)"
    resources:
      inputs:
        - name: project-level3
          resource: project-level3