apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: pipetest
spec:
  pipelineRef:
    name: test-pipeline
  serviceAccountName: front-svc-acc 
  resources:
    - name: level3-project
      resourceRef: 
        name: e2e-js-test-src 