apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: e2e-test-taskrun
spec:
  serviceAccountName: front-svc-acc 
  taskRef:
    name: e2e-test
  params:
  - name: IMAGE
    value: "walaafahad/e2e-js-test"
  resources:
    inputs:
    - name: level3-project
      resourceRef:
        name: e2e-js-test-src