 
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: e2e-task-run
spec:
  resources:
    inputs:
    - name: level3-project
      type: git
  steps:
  - name: run-test
    image: walaafahad/e2e-js-test
    workingDir: /workspace/level3-project/src
    command: ["/bin/sh"]
    args: ["-c", "/e2e-js-test/runner.sh"]