apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: test-run
spec:
  taskRef:
    name: run-e2e-test
  resources:
    inputs:
      - name: level3-project
        resourceRef:
          name:  e2e-js-test-src 