apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: role-socks-shop
rules:
- apiGroups: ["serving.knative.dev", "apps", "", "extensions"]
  resources: ["services", "deployments", "deployments.apps", "replicasets", "pods", "ingresses"]
  verbs: ["get", "create", "update", "patch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sock-shop-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: role-socks-shop
subjects:
- kind: ServiceAccount
  name: catlog-svc-acc
  namespace: test
