apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: walaafahad/user
        ports:
        - containerPort: 80
        securityContext:
          runAsUser: 0
        env:
        - name: MONGO_HOST
          value: user-db:27017
      nodeSelector:
        beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    app: user
  namespace: test
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: user
